@extends('layouts.turtube')

@section('title', 'Platform Analitiği')

@section('content')
<div class="mx-auto max-w-7xl space-y-8">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-red-400">Yönetim</p><h1 class="mt-2 text-4xl font-bold text-white">Platform analitiği</h1></div><form method="GET"><select name="period" onchange="this.form.submit()" class="rounded-xl border border-gray-700 bg-gray-900 px-4 py-2 text-white">@foreach ([7, 30, 365] as $value)<option value="{{ $value }}" @selected($days === $value)>Son {{ $value }} gün</option>@endforeach</select></form></div>
    @php($formatDuration = fn (int $seconds) => intdiv($seconds, 3600).' sa '.intdiv($seconds % 3600, 60).' dk')
    <div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><x-ui.card class="p-6"><p class="text-sm text-gray-400">Görüntülenme</p><p class="mt-3 text-3xl font-bold text-white">{{ number_format($stats['views']) }}</p></x-ui.card><x-ui.card class="p-6"><p class="text-sm text-gray-400">İzlenme süresi</p><p class="mt-3 text-3xl font-bold text-white">{{ $formatDuration($stats['watchTime']) }}</p></x-ui.card><x-ui.card class="p-6"><p class="text-sm text-gray-400">Beğeni</p><p class="mt-3 text-3xl font-bold text-white">{{ number_format($stats['likes']) }}</p></x-ui.card><x-ui.card class="p-6"><p class="text-sm text-gray-400">Yorum</p><p class="mt-3 text-3xl font-bold text-white">{{ number_format($stats['comments']) }}</p></x-ui.card></div>
    <x-ui.card class="p-6"><h2 class="text-xl font-bold text-white">Günlük görüntülenme</h2>@php($maxViews = max(1, $chart->max('views')))<div class="mt-6 flex h-64 items-end gap-1.5">@foreach ($chart as $index => $point)<div class="group flex min-w-0 flex-1 flex-col justify-end"><div title="{{ number_format($point['views']) }} görüntülenme" class="min-h-1 rounded-t bg-gradient-to-t from-red-700 to-red-400" style="height: {{ max(2, ($point['views'] / $maxViews) * 100) }}%"></div>@if ($index % max(1, intdiv($chart->count(), 8)) === 0)<span class="mt-2 overflow-hidden text-center text-[10px] text-gray-500">{{ $point['label'] }}</span>@endif</div>@endforeach</div></x-ui.card>
    <x-ui.card class="overflow-hidden"><div class="border-b border-gray-800 px-6 py-4"><h2 class="text-xl font-bold text-white">En çok izlenen videolar</h2></div><div class="divide-y divide-gray-800">@forelse ($topVideos as $video)<div class="flex items-center justify-between gap-4 px-6 py-4"><div class="min-w-0"><a href="{{ route('videos.show', $video) }}" class="line-clamp-1 font-semibold text-white hover:text-red-400">{{ $video->title }}</a><p class="mt-1 text-sm text-gray-400">{{ $video->user->name }}</p></div><p class="shrink-0 font-bold text-white">{{ number_format($video->views) }}</p></div>@empty<p class="p-6 text-gray-400">Veri bulunamadı.</p>@endforelse</div></x-ui.card>
</div>
@endsection
