@extends('layouts.turtube')

@section('title', 'Sistem Yönetimi')

@section('content')
<div class="mx-auto max-w-5xl">
    <div class="mb-8"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-red-400">Sistem yönetimi</p><h1 class="mt-2 text-4xl font-bold text-white">Site ayarları</h1><p class="mt-2 text-gray-400">Marka görünümü, duyurular ve bakım modu.</p></div>
    <form method="POST" enctype="multipart/form-data" action="{{ route('admin.settings.update') }}" class="space-y-6">@csrf @method('PUT')
        <x-ui.card class="p-6"><h2 class="text-xl font-bold text-white">Marka</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><label><span class="mb-2 block text-sm font-medium text-gray-300">Site adı</span><input name="site_name" required maxlength="100" value="{{ old('site_name', $settings->site_name) }}" class="w-full rounded-xl border border-gray-700 bg-gray-950 px-4 py-3 text-white"></label><div></div><label><span class="mb-2 block text-sm font-medium text-gray-300">Logo</span><input name="logo" type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" class="block w-full text-sm text-gray-300">@if($settings->logo)<img src="{{ asset('storage/'.$settings->logo) }}" alt="Mevcut logo" class="mt-3 h-12 max-w-40 object-contain object-left">@endif</label><label><span class="mb-2 block text-sm font-medium text-gray-300">Site bannerı</span><input name="banner" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full text-sm text-gray-300">@if($settings->banner)<img src="{{ asset('storage/'.$settings->banner) }}" alt="Mevcut banner" class="mt-3 h-20 w-full rounded-lg object-cover">@endif</label></div></x-ui.card>
        <x-ui.card class="p-6"><h2 class="text-xl font-bold text-white">Duyuru</h2><label class="mt-5 flex items-center gap-3 text-sm text-white"><input type="checkbox" name="announcement_enabled" value="1" @checked(old('announcement_enabled', $settings->announcement_enabled)) class="rounded border-gray-600 bg-gray-950 text-red-600"> Ziyaretçilere duyuruyu göster</label><textarea name="announcement" rows="4" maxlength="2000" placeholder="Örnek: Yeni özellikler yayında!" class="mt-4 w-full rounded-xl border border-gray-700 bg-gray-950 px-4 py-3 text-white">{{ old('announcement', $settings->announcement) }}</textarea></x-ui.card>
        <x-ui.card class="border-amber-500/30 p-6"><h2 class="text-xl font-bold text-amber-200">Bakım modu</h2><p class="mt-2 text-sm text-gray-400">Açıkken yönetici dışındaki tüm ziyaretçiler 503 bakım ekranına yönlendirilir.</p><label class="mt-5 flex items-center gap-3 text-sm text-white"><input type="checkbox" name="maintenance_mode" value="1" @checked(old('maintenance_mode', $settings->maintenance_mode)) class="rounded border-gray-600 bg-gray-950 text-red-600"> Bakım modunu etkinleştir</label><textarea name="maintenance_message" rows="4" maxlength="2000" placeholder="Bakım mesajı" class="mt-4 w-full rounded-xl border border-gray-700 bg-gray-950 px-4 py-3 text-white">{{ old('maintenance_message', $settings->maintenance_message) }}</textarea></x-ui.card>
        <div class="flex justify-end"><button class="rounded-xl bg-red-600 px-6 py-3 font-semibold text-white hover:bg-red-500">Ayarları kaydet</button></div>
    </form>
</div>
@endsection
